import type { DailyMapPoint } from './daily-map';

// Coordinates identify places or areas, not entrances or walking routes.
export const dailyMapPoints: DailyMapPoint[] = [
  {
    "id": "09-29-heathrow",
    "date": "09/29",
    "name": "希思罗机场",
    "englishName": "Heathrow Airport",
    "lat": 51.47,
    "lng": -0.4543,
    "kind": "transport",
    "scope": "connection",
    "note": "机场范围示意；实际航站楼按机票。入境后坐 Piccadilly line 到 Earl’s Court。",
    "query": "Heathrow Airport London UK",
    "source": "local route-map.tsx; airport area"
  },
  {
    "id": "09-29-earls",
    "date": "09/29",
    "name": "伯爵宫地铁站",
    "englishName": "Earl’s Court",
    "lat": 51.4913,
    "lng": -0.1947,
    "kind": "transport",
    "scope": "local",
    "note": "车站位置示意，不代表具体出口；回程复用。",
    "query": "Earl’s Court London UK",
    "source": "https://en.wikipedia.org/wiki/Earl%27s_Court_tube_station"
  },
  {
    "id": "09-29-barmy",
    "date": "09/29",
    "name": "伦敦青旅",
    "englishName": "Barmy Badger Backpackers",
    "lat": 51.4934957,
    "lng": -0.1959131,
    "kind": "stay",
    "scope": "local",
    "note": "17 Longridge Road，出发与回程复用同一住宿点。",
    "query": "Barmy Badger Backpackers 17 Longridge Road London",
    "source": "https://www.openstreetmap.org/way/31870112"
  },
  {
    "id": "09-29-borough",
    "date": "09/29",
    "name": "博罗市场",
    "englishName": "Borough Market",
    "lat": 51.50556,
    "lng": -0.09083,
    "kind": "food",
    "scope": "local",
    "note": "午餐候选，落地延误可就近替换。地图标记市场范围。",
    "query": "Borough Market London UK",
    "source": "https://en.wikipedia.org/wiki/Borough_Market"
  },
  {
    "id": "09-29-stoney",
    "date": "09/29",
    "name": "破釜酒吧外景门口",
    "englishName": "7 Stoney Street",
    "lat": 51.5051,
    "lng": -0.0909,
    "kind": "sight",
    "scope": "local",
    "note": "斯托尼街外景区域点；找 7 Stoney Street 门面，不进入私人区域。累了可跳过。",
    "query": "7 Stoney Street London",
    "source": "https://www.framepin.co/en/location/stoney-street"
  },
  {
    "id": "09-29-hays",
    "date": "09/29",
    "name": "海斯拱廊",
    "englishName": "Hay’s Galleria",
    "lat": 51.5058,
    "lng": -0.0837,
    "kind": "sight",
    "scope": "local",
    "note": "具名地点或街区位置示意；现场入口与开放范围以标识为准。",
    "query": "Hay’s Galleria London UK",
    "source": "https://en.wikipedia.org/wiki/Hay%27s_Galleria"
  },
  {
    "id": "09-29-potters",
    "date": "09/29",
    "name": "塔桥南岸公园",
    "englishName": "Potters Fields Park",
    "lat": 51.5042,
    "lng": -0.0786,
    "kind": "sight",
    "scope": "local",
    "note": "公园区域点，按体力休息与拍照。",
    "query": "Potters Fields Park London UK",
    "source": "https://en.wikipedia.org/wiki/Potters_Fields_Park"
  },
  {
    "id": "09-29-tower",
    "date": "09/29",
    "name": "塔桥",
    "englishName": "Tower Bridge",
    "lat": 51.5056,
    "lng": -0.0753,
    "kind": "sight",
    "scope": "local",
    "note": "桥梁位置示意。下午外观；晚饭后有体力可回看夜景，不重复标点。",
    "query": "Tower Bridge London UK",
    "source": "https://en.wikipedia.org/wiki/Tower_Bridge"
  },
  {
    "id": "09-29-honest",
    "date": "09/29",
    "name": "汉堡晚餐候选",
    "englishName": "Honest Burgers · London Bridge",
    "lat": 51.504618,
    "lng": -0.085867,
    "kind": "food",
    "scope": "local",
    "note": "晚餐候选：6 Bermondsey Street；实际营业当天确认。",
    "query": "Honest Burgers London Bridge 6 Bermondsey Street",
    "source": "https://foodhygienescan.co.uk/establishment/1177103"
  },
  {
    "id": "09-30-barmy",
    "date": "09/30",
    "name": "伦敦青旅",
    "englishName": "Barmy Badger Backpackers",
    "lat": 51.4934957,
    "lng": -0.1959131,
    "kind": "stay",
    "scope": "local",
    "note": "17 Longridge Road，出发与回程复用同一住宿点。",
    "query": "Barmy Badger Backpackers 17 Longridge Road London",
    "source": "https://www.openstreetmap.org/way/31870112"
  },
  {
    "id": "09-30-buckingham",
    "date": "09/30",
    "name": "白金汉宫",
    "englishName": "Buckingham Palace",
    "lat": 51.50083,
    "lng": -0.14194,
    "kind": "sight",
    "scope": "local",
    "note": "王宫建筑范围点，上午看外观；不代表入场入口。换岗待官方日历确认。",
    "query": "Buckingham Palace London UK",
    "source": "https://en.wikipedia.org/wiki/Buckingham_Palace"
  },
  {
    "id": "09-30-stjamess",
    "date": "09/30",
    "name": "圣詹姆斯公园",
    "englishName": "St James’s Park",
    "lat": 51.5025,
    "lng": -0.135,
    "kind": "sight",
    "scope": "local",
    "note": "公园区域点，沿开放步道向威斯敏斯特走。",
    "query": "St James’s Park London UK",
    "source": "https://en.wikipedia.org/wiki/St_James%27s_Park"
  },
  {
    "id": "09-30-westarms",
    "date": "09/30",
    "name": "午餐候选 · 英式酒吧",
    "englishName": "Westminster Arms",
    "lat": 51.50056,
    "lng": -0.12981,
    "kind": "food",
    "scope": "local",
    "note": "9–10 Storeys Gate，午餐候选。",
    "query": "Westminster Arms 9 10 Storeys Gate London",
    "source": "https://mapcarta.com/W545664029"
  },
  {
    "id": "09-30-bigben",
    "date": "09/30",
    "name": "大本钟",
    "englishName": "Big Ben",
    "lat": 51.5007,
    "lng": -0.1245,
    "kind": "sight",
    "scope": "local",
    "note": "建筑范围点，外观拍照；不是售票入口。",
    "query": "Big Ben London UK",
    "source": "https://en.wikipedia.org/wiki/Big_Ben"
  },
  {
    "id": "09-30-parliament",
    "date": "09/30",
    "name": "议会广场",
    "englishName": "Parliament Square",
    "lat": 51.50056,
    "lng": -0.12667,
    "kind": "sight",
    "scope": "local",
    "note": "广场区域点，与大本钟、教堂同一区域。",
    "query": "Parliament Square London UK",
    "source": "https://en.wikipedia.org/wiki/Parliament_Square"
  },
  {
    "id": "09-30-abbey",
    "date": "09/30",
    "name": "威斯敏斯特教堂",
    "englishName": "Westminster Abbey",
    "lat": 51.49944,
    "lng": -0.1275,
    "kind": "sight",
    "scope": "local",
    "note": "建筑范围点；入内可选，需按预约入口和时段，不是必去项目。",
    "query": "Westminster Abbey London UK",
    "source": "https://en.wikipedia.org/wiki/Westminster_Abbey"
  },
  {
    "id": "09-30-trafalgar",
    "date": "09/30",
    "name": "特拉法加广场",
    "englishName": "Trafalgar Square",
    "lat": 51.50806,
    "lng": -0.12806,
    "kind": "sight",
    "scope": "local",
    "note": "广场区域点，傍晚短逛，体力不足可跳过。",
    "query": "Trafalgar Square London UK",
    "source": "https://en.wikipedia.org/wiki/Trafalgar_Square"
  },
  {
    "id": "09-30-piccadilly",
    "date": "09/30",
    "name": "皮卡迪利广场 · 影视街景",
    "englishName": "Piccadilly Circus",
    "lat": 51.51,
    "lng": -0.13444,
    "kind": "sight",
    "scope": "local",
    "note": "公共广场区域点，《哈利·波特》街景顺路外观约 10–15 分钟。",
    "query": "Piccadilly Circus London UK",
    "source": "https://en.wikipedia.org/wiki/Piccadilly_Circus"
  },
  {
    "id": "09-30-chinatown",
    "date": "09/30",
    "name": "唐人街",
    "englishName": "Chinatown",
    "lat": 51.51111,
    "lng": -0.13139,
    "kind": "sight",
    "scope": "local",
    "note": "Gerrard Street 一带的街区区域点。",
    "query": "Chinatown London UK",
    "source": "https://en.wikipedia.org/wiki/Chinatown,_London"
  },
  {
    "id": "09-30-dumplings",
    "date": "09/30",
    "name": "晚餐候选 · 小笼包",
    "englishName": "Dumplings’ Legend",
    "lat": 51.5117,
    "lng": -0.1313,
    "kind": "food",
    "scope": "local",
    "note": "15–16 Gerrard Street 晚餐候选。标记使用门面附近拍摄坐标作街区定位，不是精确店门。",
    "query": "Dumplings Legend 15 16 Gerrard Street London",
    "source": "https://commons.wikimedia.org/wiki/File:Dumplings%27_Legend_-_2024-08-21.jpg"
  },
  {
    "id": "10-01-barmy",
    "date": "10/01",
    "name": "伦敦青旅",
    "englishName": "Barmy Badger Backpackers",
    "lat": 51.4934957,
    "lng": -0.1959131,
    "kind": "stay",
    "scope": "connection",
    "note": "17 Longridge Road，出发与回程复用同一住宿点。",
    "query": "Barmy Badger Backpackers 17 Longridge Road London",
    "source": "https://www.openstreetmap.org/way/31870112"
  },
  {
    "id": "10-01-earls",
    "date": "10/01",
    "name": "伯爵宫地铁站",
    "englishName": "Earl’s Court",
    "lat": 51.4913,
    "lng": -0.1947,
    "kind": "transport",
    "scope": "connection",
    "note": "车站位置示意，不代表具体出口；回程复用。",
    "query": "Earl’s Court London UK",
    "source": "https://en.wikipedia.org/wiki/Earl%27s_Court_tube_station"
  },
  {
    "id": "10-01-kingscross_tube",
    "date": "10/01",
    "name": "国王十字圣潘克拉斯地铁站",
    "englishName": "King’s Cross St Pancras",
    "lat": 51.5302,
    "lng": -0.1241,
    "kind": "transport",
    "scope": "connection",
    "note": "这是地铁站。按 National Rail / King’s Cross 标识转到国王十字国铁站，不去相邻 St Pancras 国铁站台。",
    "query": "Kings Cross St Pancras Underground Station London",
    "source": "https://en.wikipedia.org/wiki/King%27s_Cross_St_Pancras_tube_station"
  },
  {
    "id": "10-01-kingscross",
    "date": "10/01",
    "name": "国王十字火车站",
    "englishName": "London King’s Cross",
    "lat": 51.531,
    "lng": -0.1233,
    "kind": "transport",
    "scope": "connection",
    "note": "国铁车站位置示意；候车、站台以实际车票和站内显示为准，回程复用。",
    "query": "London Kings Cross Station",
    "source": "https://en.wikipedia.org/wiki/London_King%27s_Cross_railway_station"
  },
  {
    "id": "10-01-cambridge_station",
    "date": "10/01",
    "name": "剑桥火车站",
    "englishName": "Cambridge Station",
    "lat": 52.1942,
    "lng": 0.1375,
    "kind": "transport",
    "scope": "local",
    "note": "到达及返程复用；是 Cambridge，不是 Cambridge North。到老城约 25–30 分钟步行。",
    "query": "Cambridge Railway Station Station Road",
    "source": "https://en.wikipedia.org/wiki/Cambridge_railway_station"
  },
  {
    "id": "10-01-kingsparade",
    "date": "10/01",
    "name": "国王大道",
    "englishName": "King’s Parade",
    "lat": 52.2046,
    "lng": 0.1177,
    "kind": "sight",
    "scope": "local",
    "note": "公共街区位置点，按学院预约调整顺序。",
    "query": "King’s Parade Cambridge UK",
    "source": "https://en.wikipedia.org/wiki/King%27s_Parade"
  },
  {
    "id": "10-01-chapel",
    "date": "10/01",
    "name": "国王学院礼拜堂",
    "englishName": "King’s College Chapel",
    "lat": 52.2048,
    "lng": 0.1165,
    "kind": "sight",
    "scope": "local",
    "note": "礼拜堂建筑范围点，具体入场口按订单和标识；门票、时段待预订。",
    "query": "Kings College Chapel Cambridge",
    "source": "https://en.wikipedia.org/wiki/King%27s_College_Chapel,_Cambridge"
  },
  {
    "id": "10-01-cambridge_market",
    "date": "10/01",
    "name": "午餐候选 · 剑桥市场",
    "englishName": "Cambridge Market Square",
    "lat": 52.2054,
    "lng": 0.1191,
    "kind": "food",
    "scope": "local",
    "note": "集市广场范围点；午餐摊位候选，以当天为准。",
    "query": "Cambridge Market Square Market Hill",
    "source": "https://en.wikipedia.org/wiki/Market_Hill,_Cambridge"
  },
  {
    "id": "10-01-punt",
    "date": "10/01",
    "name": "可选 · 康河撑篙码头",
    "englishName": "Mill Lane Punting Station",
    "lat": 52.20158,
    "lng": 0.11645,
    "kind": "sight",
    "scope": "local",
    "note": "可选撑篙，与 The Backs 河畔散步二选一。坐标取运营商嵌入地图中心作码头附近示意，具体集合点以实际所订运营商为准；尚未预订。",
    "query": "Mill Lane Punting Station Cambridge",
    "source": "https://www.scudamores.com/punting-mill-lane"
  },
  {
    "id": "10-01-backs",
    "date": "10/01",
    "name": "可选 · 学院后园河畔",
    "englishName": "The Backs",
    "lat": 52.20437,
    "lng": 0.11404,
    "kind": "sight",
    "scope": "local",
    "note": "河畔区域点，与撑篙二选一，不是追加必去。按开放公共步道走，不进入未开放学院。",
    "query": "The Backs Cambridge",
    "source": "https://en.wikipedia.org/wiki/The_Backs"
  },
  {
    "id": "10-01-trinity",
    "date": "10/01",
    "name": "三一街",
    "englishName": "Trinity Street",
    "lat": 52.2063,
    "lng": 0.1182,
    "kind": "sight",
    "scope": "local",
    "note": "三一街街区范围点，不新增学院入内参观。",
    "query": "Trinity Street Cambridge",
    "source": "https://en.wikipedia.org/wiki/Trinity_Street,_Cambridge"
  },
  {
    "id": "10-01-eagle",
    "date": "10/01",
    "name": "早晚餐候选 · 老鹰酒吧",
    "englishName": "The Eagle",
    "lat": 52.204,
    "lng": 0.1182,
    "kind": "food",
    "scope": "local",
    "note": "建议早晚餐候选，随后复用剑桥站返回伦敦；时间以车票为准。",
    "query": "The Eagle Benet Street Cambridge",
    "source": "https://en.wikipedia.org/wiki/The_Eagle,_Cambridge"
  },
  {
    "id": "10-01-platform934",
    "date": "10/01",
    "name": "返伦敦后可选 · 9¾ 站台推车",
    "englishName": "Platform 9¾ · King’s Cross",
    "lat": 51.532,
    "lng": -0.1233,
    "kind": "sight",
    "scope": "connection",
    "note": "仅在剑桥返程后可选拍照。车站大厅内主题推车，不是真实铁路站台；排队长或太晚可跳过。标记为大厅附近区域点。",
    "query": "Harry Potter Platform 9 3/4 Kings Cross London",
    "source": "https://magicinlondon.co.uk/locations"
  },
  {
    "id": "10-02-barmy",
    "date": "10/02",
    "name": "伦敦青旅",
    "englishName": "Barmy Badger Backpackers",
    "lat": 51.4934957,
    "lng": -0.1959131,
    "kind": "stay",
    "scope": "local",
    "note": "17 Longridge Road，出发与回程复用同一住宿点。",
    "query": "Barmy Badger Backpackers 17 Longridge Road London",
    "source": "https://www.openstreetmap.org/way/31870112"
  },
  {
    "id": "10-02-earls",
    "date": "10/02",
    "name": "伯爵宫地铁站",
    "englishName": "Earl’s Court",
    "lat": 51.4913,
    "lng": -0.1947,
    "kind": "transport",
    "scope": "local",
    "note": "车站位置示意，不代表具体出口；回程复用。",
    "query": "Earl’s Court London UK",
    "source": "https://en.wikipedia.org/wiki/Earl%27s_Court_tube_station"
  },
  {
    "id": "10-02-southfields",
    "date": "10/02",
    "name": "Southfields 地铁站",
    "englishName": "Southfields",
    "lat": 51.445,
    "lng": -0.207,
    "kind": "transport",
    "scope": "local",
    "note": "下车后步行去 Gate 4；返程复用此站。",
    "query": "Southfields Underground Station London",
    "source": "https://en.wikipedia.org/wiki/Southfields_tube_station"
  },
  {
    "id": "10-02-wimbledon",
    "date": "10/02",
    "name": "温布尔登网球博物馆",
    "englishName": "Wimbledon Lawn Tennis Museum",
    "lat": 51.434722,
    "lng": -0.213333,
    "kind": "sight",
    "scope": "local",
    "note": "场馆位置示意，不代表 Gate 4 精确入口；参观从 Church Road Gate 4 进入，沿现场指示。轻量参观约 1–1.5 小时，尚未购票。",
    "query": "Wimbledon Lawn Tennis Museum Gate 4 Church Road London SW19 5AG",
    "source": "https://www.wikidata.org/wiki/Q2583240"
  },
  {
    "id": "10-02-speedys",
    "date": "10/02",
    "name": "夏洛克外景门口",
    "englishName": "Speedy’s Café · 187 North Gower Street",
    "lat": 51.52619,
    "lng": -0.1369017,
    "kind": "sight",
    "scope": "local",
    "note": "BBC《神探夏洛克》221B 外景，位于 North Gower Street；不是贝克街博物馆。外观拍照。",
    "query": "Speedys Sandwich Bar Cafe 187 North Gower Street London NW1 2NJ",
    "source": "https://tripomatic.com/en/poi/speedy-s-poi%3A50909"
  },
  {
    "id": "10-02-masterwei",
    "date": "10/02",
    "name": "午餐候选 · 西安面馆",
    "englishName": "Master Wei · Bloomsbury",
    "lat": 51.5212,
    "lng": -0.12262,
    "kind": "food",
    "scope": "local",
    "note": "13 Cosmo Place，博物馆前午餐候选，排队久可就近换一家。",
    "query": "Master Wei 13 Cosmo Place Bloomsbury London",
    "source": "https://mapcarta.com/N12406028801"
  },
  {
    "id": "10-02-british",
    "date": "10/02",
    "name": "大英博物馆",
    "englishName": "British Museum",
    "lat": 51.5194,
    "lng": -0.1269,
    "kind": "sight",
    "scope": "local",
    "note": "建筑位置示意，入场入口和时段以预约为准；建议 14:00–17:00。",
    "query": "British Museum London UK",
    "source": "https://en.wikipedia.org/wiki/British_Museum"
  },
  {
    "id": "10-02-covent",
    "date": "10/02",
    "name": "科文特花园",
    "englishName": "Covent Garden",
    "lat": 51.5125,
    "lng": -0.1225,
    "kind": "sight",
    "scope": "local",
    "note": "街区范围点；博物馆后短逛，按体力缩短。",
    "query": "Covent Garden London UK",
    "source": "https://en.wikipedia.org/wiki/Covent_Garden"
  },
  {
    "id": "10-02-sevendials",
    "date": "10/02",
    "name": "七晷街区",
    "englishName": "Seven Dials",
    "lat": 51.51375,
    "lng": -0.127028,
    "kind": "sight",
    "scope": "local",
    "note": "七街交汇区域；时间不足可直接去美食市场。",
    "query": "Seven Dials London UK",
    "source": "https://en.wikipedia.org/wiki/Seven_Dials,_London"
  },
  {
    "id": "10-02-dialsmarket",
    "date": "10/02",
    "name": "晚餐候选 · 七晷美食市场",
    "englishName": "Seven Dials Market",
    "lat": 51.51412,
    "lng": -0.12581,
    "kind": "food",
    "scope": "local",
    "note": "晚餐候选，之后买好白崖水和便携午餐；未指定超市不标点。",
    "query": "Seven Dials Market London UK",
    "source": "https://mapcarta.com/N7277566692"
  },
  {
    "id": "10-03-barmy",
    "date": "10/03",
    "name": "伦敦青旅",
    "englishName": "Barmy Badger Backpackers",
    "lat": 51.4934957,
    "lng": -0.1959131,
    "kind": "stay",
    "scope": "connection",
    "note": "17 Longridge Road，出发与回程复用同一住宿点。",
    "query": "Barmy Badger Backpackers 17 Longridge Road London",
    "source": "https://www.openstreetmap.org/way/31870112"
  },
  {
    "id": "10-03-earls",
    "date": "10/03",
    "name": "伯爵宫地铁站",
    "englishName": "Earl’s Court",
    "lat": 51.4913,
    "lng": -0.1947,
    "kind": "transport",
    "scope": "connection",
    "note": "车站位置示意，不代表具体出口；回程复用。",
    "query": "Earl’s Court London UK",
    "source": "https://en.wikipedia.org/wiki/Earl%27s_Court_tube_station"
  },
  {
    "id": "10-03-victoria",
    "date": "10/03",
    "name": "维多利亚火车站",
    "englishName": "London Victoria",
    "lat": 51.4952,
    "lng": -0.1441,
    "kind": "transport",
    "scope": "connection",
    "note": "伦敦出发和返回复用；经 Lewes 换乘去 Seaford。不是已购票或已确认车次。",
    "query": "London Victoria Station",
    "source": "https://en.wikipedia.org/wiki/London_Victoria_station"
  },
  {
    "id": "10-03-lewes",
    "date": "10/03",
    "name": "刘易斯火车换乘",
    "englishName": "Lewes Station",
    "lat": 50.87083,
    "lng": 0.01167,
    "kind": "transport",
    "scope": "connection",
    "note": "去回程铁路换乘点，实际站台与时间按车票。",
    "query": "Lewes Railway Station East Sussex",
    "source": "https://en.wikipedia.org/wiki/Lewes_railway_station"
  },
  {
    "id": "10-03-seaford",
    "date": "10/03",
    "name": "锡福德火车站",
    "englishName": "Seaford Station",
    "lat": 50.773,
    "lng": 0.1,
    "kind": "transport",
    "scope": "local",
    "note": "到达与返程复用；步行到 Seaford Library 附近接公交。",
    "query": "Seaford Railway Station East Sussex",
    "source": "https://en.wikipedia.org/wiki/Seaford_railway_station_(England)"
  },
  {
    "id": "10-03-library",
    "date": "10/03",
    "name": "图书馆附近公交接驳",
    "englishName": "Seaford Library",
    "lat": 50.77365,
    "lng": 0.10316,
    "kind": "transport",
    "scope": "local",
    "note": "标记图书馆建筑附近，不是具体站牌；去程乘 12 路往 Eastbourne，到 Seven Sisters Park Centre 下车。现场确认道路哪侧。",
    "query": "Seaford Library East Sussex",
    "source": "https://mapcarta.com/W82948358"
  },
  {
    "id": "10-03-exceat",
    "date": "10/03",
    "name": "公交下车／回程与自带午餐",
    "englishName": "Seven Sisters Visitor Centre · Exceat",
    "lat": 50.77522,
    "lng": 0.15333,
    "kind": "transport",
    "scope": "local",
    "note": "游客中心地标；附近 Seven Sisters Park Centre 公交站下车，在此附近吃自带午餐。回程去反方向站牌，确认往 Seaford / Brighton；不是两方向同一上车点。",
    "query": "Seven Sisters Country Park Visitor Centre Exceat",
    "source": "https://mapcarta.com/N9722399802; local route-map.tsx"
  },
  {
    "id": "10-03-bridge",
    "date": "10/03",
    "name": "过桥至河西岸",
    "englishName": "Exceat Bridge",
    "lat": 50.77344,
    "lng": 0.14572,
    "kind": "sight",
    "scope": "local",
    "note": "经桥过到 River Cuckmere 西岸，再沿正式开放步道向南；回程原路过桥。",
    "query": "Exceat Bridge East Sussex",
    "source": "local components/route-map.tsx"
  },
  {
    "id": "10-03-cottages",
    "date": "10/03",
    "name": "白崖西岸小屋观景点",
    "englishName": "Coastguard Cottages",
    "lat": 50.75869,
    "lng": 0.14521,
    "kind": "sight",
    "scope": "local",
    "note": "仅走西岸小屋观景短线，往返加拍照留约 2–3 小时；原路返回 Exceat。不涉水横渡河口，不靠崖边，不加 Birling Gap。",
    "query": "Coastguard Cottages Cuckmere Haven Seaford",
    "source": "local components/route-map.tsx"
  },
  {
    "id": "10-03-markethalls",
    "date": "10/03",
    "name": "回伦敦晚餐候选",
    "englishName": "Market Halls Victoria",
    "lat": 51.49631,
    "lng": -0.1445,
    "kind": "food",
    "scope": "connection",
    "note": "回伦敦后 191 Victoria Street 晚餐候选；建筑附近点，不承诺具体入口。",
    "query": "Market Halls 191 Victoria Street London",
    "source": "https://commons.wikimedia.org/wiki/File:Market_Halls,_Victoria_-_geograph.org.uk_-_7977104.jpg"
  },
  {
    "id": "10-04-barmy",
    "date": "10/04",
    "name": "伦敦青旅",
    "englishName": "Barmy Badger Backpackers",
    "lat": 51.4934957,
    "lng": -0.1959131,
    "kind": "stay",
    "scope": "connection",
    "note": "17 Longridge Road；今天退房，带齐全部行李北上。",
    "query": "Barmy Badger Backpackers 17 Longridge Road London",
    "source": "https://www.openstreetmap.org/way/31870112"
  },
  {
    "id": "10-04-earls",
    "date": "10/04",
    "name": "伯爵宫地铁站",
    "englishName": "Earl’s Court",
    "lat": 51.4913,
    "lng": -0.1947,
    "kind": "transport",
    "scope": "connection",
    "note": "车站位置示意，不代表具体出口；今天单程北上。",
    "query": "Earl’s Court London UK",
    "source": "https://en.wikipedia.org/wiki/Earl%27s_Court_tube_station"
  },
  {
    "id": "10-04-kingscross_tube",
    "date": "10/04",
    "name": "国王十字圣潘克拉斯地铁站",
    "englishName": "King’s Cross St Pancras",
    "lat": 51.5302,
    "lng": -0.1241,
    "kind": "transport",
    "scope": "connection",
    "note": "这是地铁站。按 National Rail / King’s Cross 标识转到国王十字国铁站，不去相邻 St Pancras 国铁站台。",
    "query": "Kings Cross St Pancras Underground Station London",
    "source": "https://en.wikipedia.org/wiki/King%27s_Cross_St_Pancras_tube_station"
  },
  {
    "id": "10-04-kingscross",
    "date": "10/04",
    "name": "国王十字火车站",
    "englishName": "London King’s Cross",
    "lat": 51.531,
    "lng": -0.1233,
    "kind": "transport",
    "scope": "connection",
    "note": "国铁车站位置示意；候车、站台以实际车票和站内显示为准，今天单程北上。",
    "query": "London Kings Cross Station",
    "source": "https://en.wikipedia.org/wiki/London_King%27s_Cross_railway_station"
  },
  {
    "id": "10-04-waverley",
    "date": "10/04",
    "name": "爱丁堡威瓦利火车站",
    "englishName": "Edinburgh Waverley",
    "lat": 55.9521,
    "lng": -3.1893,
    "kind": "transport",
    "scope": "local",
    "note": "抵达后的车站位置示意；去住宿最后一段上坡。",
    "query": "Edinburgh Waverley Edinburgh UK",
    "source": "https://en.wikipedia.org/wiki/Edinburgh_Waverley_railway_station"
  },
  {
    "id": "10-04-castle_rock",
    "date": "10/04",
    "name": "城堡岩青旅",
    "englishName": "Castle Rock Hostel",
    "lat": 55.94821,
    "lng": -3.19594,
    "kind": "stay",
    "scope": "local",
    "note": "15 Johnston Terrace；城堡脚下住宿，入住和返回复用。",
    "query": "Castle Rock Hostel 15 Johnston Terrace Edinburgh EH1 2PW",
    "source": "https://hotels.cloudbeds.com/en/reservation/4TYHDm?rid=112602"
  },
  {
    "id": "10-04-bookingoffice",
    "date": "10/04",
    "name": "到达后晚餐候选",
    "englishName": "The Booking Office",
    "lat": 55.95173,
    "lng": -3.19157,
    "kind": "food",
    "scope": "local",
    "note": "17 Waverley Bridge 晚餐候选。地图建筑范围点；晚到按实际营业换就近热食。",
    "query": "The Booking Office 17 Waverley Bridge Edinburgh",
    "source": "https://www.geograph.org.uk/photo/6275389"
  },
  {
    "id": "10-05-castle_rock",
    "date": "10/05",
    "name": "城堡岩青旅",
    "englishName": "Castle Rock Hostel",
    "lat": 55.94821,
    "lng": -3.19594,
    "kind": "stay",
    "scope": "local",
    "note": "15 Johnston Terrace；城堡脚下住宿，入住和返回复用。",
    "query": "Castle Rock Hostel 15 Johnston Terrace Edinburgh EH1 2PW",
    "source": "https://hotels.cloudbeds.com/en/reservation/4TYHDm?rid=112602"
  },
  {
    "id": "10-05-castle",
    "date": "10/05",
    "name": "爱丁堡城堡",
    "englishName": "Edinburgh Castle",
    "lat": 55.94861,
    "lng": -3.20083,
    "kind": "sight",
    "scope": "local",
    "note": "城堡范围点，不是精确入口；按预约时间，经 Castlehill 正常入口进入。",
    "query": "Edinburgh Castle",
    "source": "https://en.wikipedia.org/wiki/Edinburgh_Castle"
  },
  {
    "id": "10-05-oink",
    "date": "10/05",
    "name": "午餐候选 · 烤猪肉卷",
    "englishName": "Oink · Victoria Street",
    "lat": 55.948607,
    "lng": -3.1942404,
    "kind": "food",
    "scope": "local",
    "note": "34 Victoria Street 午餐候选，售完即止，不安排夜晚。",
    "query": "Oink 34 Victoria Street Edinburgh",
    "source": "https://gb.near-place.com/oink-34-victoria-street-edinburgh/de"
  },
  {
    "id": "10-05-victoria_street",
    "date": "10/05",
    "name": "维多利亚街",
    "englishName": "Victoria Street",
    "lat": 55.948623,
    "lng": -3.193919,
    "kind": "sight",
    "scope": "local",
    "note": "公共街道区域点，维多利亚街与草市场顺路短逛。",
    "query": "Victoria Street Edinburgh",
    "source": "https://www.streetlist.co.uk/eh/eh1/eh1-2/victoria-street"
  },
  {
    "id": "10-05-grassmarket",
    "date": "10/05",
    "name": "草市场",
    "englishName": "Grassmarket",
    "lat": 55.9475,
    "lng": -3.19611,
    "kind": "sight",
    "scope": "local",
    "note": "公共广场区域点，按体力慢走。",
    "query": "Grassmarket Edinburgh",
    "source": "https://en.wikipedia.org/wiki/Grassmarket"
  },
  {
    "id": "10-05-royalmile",
    "date": "10/05",
    "name": "皇家英里大道",
    "englishName": "Royal Mile",
    "lat": 55.95056,
    "lng": -3.18556,
    "kind": "sight",
    "scope": "local",
    "note": "长街范围参考点，不代表需要走完整条大道或固定集合点。",
    "query": "Royal Mile Edinburgh",
    "source": "https://en.wikipedia.org/wiki/Royal_Mile"
  },
  {
    "id": "10-05-stgiles",
    "date": "10/05",
    "name": "圣吉尔斯大教堂",
    "englishName": "St Giles’ Cathedral",
    "lat": 55.94944,
    "lng": -3.19083,
    "kind": "sight",
    "scope": "local",
    "note": "教堂建筑点，能否入内按当天开放安排。",
    "query": "St Giles Cathedral Edinburgh",
    "source": "https://en.wikipedia.org/wiki/St_Giles%27_Cathedral"
  },
  {
    "id": "10-05-marykings",
    "date": "10/05",
    "name": "可选替换 · 玛丽金小巷",
    "englishName": "The Real Mary King’s Close",
    "lat": 55.95028,
    "lng": -3.19028,
    "kind": "sight",
    "scope": "local",
    "note": "可选，用预约导览替换老城闲逛，不是追加必去。建筑位置示意，入口以订单为准。",
    "query": "The Real Mary Kings Close Edinburgh",
    "source": "https://en.wikipedia.org/wiki/Mary_King%27s_Close"
  },
  {
    "id": "10-05-makars",
    "date": "10/05",
    "name": "晚餐候选 · 土豆泥餐馆",
    "englishName": "Makars Mash Bar",
    "lat": 55.94992,
    "lng": -3.1931,
    "kind": "food",
    "scope": "local",
    "note": "9–12 Bank Street 一带晚餐候选，热门时段考虑预约。",
    "query": "Makars Mash Bar 9 12 Bank Street Edinburgh",
    "source": "https://mapcarta.com/N658120552"
  },
  {
    "id": "10-06-castle_rock",
    "date": "10/06",
    "name": "城堡岩青旅",
    "englishName": "Castle Rock Hostel",
    "lat": 55.94821,
    "lng": -3.19594,
    "kind": "stay",
    "scope": "local",
    "note": "15 Johnston Terrace；城堡脚下住宿，入住和返回复用。",
    "query": "Castle Rock Hostel 15 Johnston Terrace Edinburgh EH1 2PW",
    "source": "https://hotels.cloudbeds.com/en/reservation/4TYHDm?rid=112602"
  },
  {
    "id": "10-06-arthur",
    "date": "10/06",
    "name": "天气合适可选 · 亚瑟王座",
    "englishName": "Arthur’s Seat · Holyrood Park",
    "lat": 55.94417,
    "lng": -3.16194,
    "kind": "sight",
    "scope": "local",
    "note": "这是山体/山顶位置示意，不是登山入口或直线步道。仅天气合适时去 Holyrood Park / Arthur’s Seat；大风路滑改去博物馆，遵守现场封路。",
    "query": "Holyrood Park Edinburgh",
    "source": "https://en.wikipedia.org/wiki/Arthur%27s_Seat"
  },
  {
    "id": "10-06-nms",
    "date": "10/06",
    "name": "苏格兰国家博物馆 · 馆内午餐",
    "englishName": "National Museum of Scotland",
    "lat": 55.94694,
    "lng": -3.19,
    "kind": "sight",
    "scope": "local",
    "note": "晴天午后参观，坏天气可改上午。午餐候选 Museum Kitchen 位于同一馆内 Level 0，合并为一个地点；标记为馆舍范围。",
    "query": "National Museum of Scotland Chambers Street Edinburgh",
    "source": "https://en.wikipedia.org/wiki/National_Museum_of_Scotland"
  },
  {
    "id": "10-06-princesgarden",
    "date": "10/06",
    "name": "按体力短逛 · 王子街花园",
    "englishName": "Princes Street Gardens",
    "lat": 55.950257,
    "lng": -3.200758,
    "kind": "sight",
    "scope": "local",
    "note": "公园区域点，傍晚按体力短逛；也可直接回住宿。",
    "query": "Princes Street Gardens Edinburgh",
    "source": "https://en.wikipedia.org/wiki/Princes_Street_Gardens"
  },
  {
    "id": "10-07-castle_rock",
    "date": "10/07",
    "name": "城堡岩青旅",
    "englishName": "Castle Rock Hostel",
    "lat": 55.94821,
    "lng": -3.19594,
    "kind": "stay",
    "scope": "local",
    "note": "15 Johnston Terrace；今天退房，带齐行李去机场。",
    "query": "Castle Rock Hostel 15 Johnston Terrace Edinburgh EH1 2PW",
    "source": "https://hotels.cloudbeds.com/en/reservation/4TYHDm?rid=112602"
  },
  {
    "id": "10-07-waverleybridge",
    "date": "10/07",
    "name": "机场巴士接驳区域",
    "englishName": "Waverley Bridge · Airlink 100",
    "lat": 55.9518,
    "lng": -3.1918,
    "kind": "transport",
    "scope": "local",
    "note": "威瓦利桥范围点，乘 Airlink 100 的具体站牌按当天运营信息；与机场电车二选一。",
    "query": "Waverley Bridge Airlink 100 Edinburgh",
    "source": "https://en.wikipedia.org/wiki/Waverley_Bridge; https://www.lothianbuses.com/our-services/airport-buses/"
  },
  {
    "id": "10-07-princes_tram",
    "date": "10/07",
    "name": "备选 · 王子街机场电车站",
    "englishName": "Princes Street tram stop",
    "lat": 55.95178,
    "lng": -3.1978,
    "kind": "transport",
    "scope": "local",
    "note": "机场交通备选，与 Airlink 100 二选一；查看站台方向，不需要两个站都去。",
    "query": "Princes Street tram stop Edinburgh",
    "source": "https://mapcarta.com/N2693088951; https://edinburghtrams.com/stop/princes-street"
  },
  {
    "id": "10-07-edi",
    "date": "10/07",
    "name": "爱丁堡机场",
    "englishName": "Edinburgh Airport",
    "lat": 55.95,
    "lng": -3.3725,
    "kind": "transport",
    "scope": "local",
    "note": "机场范围点，不是精确值机柜台。目标 09:45 到机场，12:50 起飞；法兰克福中转和次日香港抵达只保留文字，不标到英国地图。",
    "query": "Edinburgh Airport",
    "source": "local components/route-map.tsx; airport area"
  }
];
